# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

countFrames <- function(source) {
    .Call('videoplayR_countFrames', PACKAGE = 'videoplayR', source)
}

getFPS <- function(source) {
    .Call('videoplayR_getFPS', PACKAGE = 'videoplayR', source)
}

rcpp_hello_world <- function() {
    .Call('videoplayR_rcpp_hello_world', PACKAGE = 'videoplayR')
}

readFrame <- function(n, source) {
    .Call('videoplayR_readFrame', PACKAGE = 'videoplayR', n, source)
}

videoDim <- function(source) {
    .Call('videoplayR_videoDim', PACKAGE = 'videoplayR', source)
}

