# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bresenham_line <- function(x1, y1, z1, x2, y2, z2) {
    .Call('videoplayR_bresenham_line', PACKAGE = 'videoplayR', x1, y1, z1, x2, y2, z2)
}

